CREATE TABLE IF NOT EXISTS "tags"(
  "id" BIGSERIAL PRIMARY KEY, 
  "name" VARCHAR UNIQUE NOT NULL, 
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, 
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL
);