version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: db
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  web:
    build: 
      context: .
      target: 'builder'
    container_name: web
    env_file: .env
    environment:
      TBLS_DOC_PATH: db/doc
    ports:
      - 8080:8080
    depends_on: 
      - db
    tty: true
    volumes:
      - .:/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target
  pgweb:
    image: sosedoff/pgweb
    container_name: pgweb
    ports: 
      - "8081:8081"
    env_file: .env
    depends_on:
      - db
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    environment: 
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp
    volumes:
      - maildir:/tmp
volumes:
  db_data:
    driver: local
  cargo-cache:
  target-cache:
  maildir:

