[config]
skip_core_tasks = true

[tasks.migrate_create]
command = "migrate"
description = "マイグレーションファイルを作成する makers migrate_create {file_name}"
args = [
  "create",
  "-ext",
  "sql",
  "-dir",
  "db/migrations",
  "-seq",
  "${@}"
]

[tasks.migrate_up]
command = "migrate"
description = "migrate upを実行 migrate_up {version}"
args = [
  "-database",
  "${POSTGRES_URL}",
  "-path",
  "db/migrations",
  "up",
  "${@}"
]


[tasks.migrate_down]
command = "migrate"
description = "migrate upを実行 migrate_down {version}"
args = [
  "-database",
  "${POSTGRES_URL}",
  "-path",
  "db/migrations",
  "down",
  "${@}"
]

[tasks.migrate_force]
command = "migrate"
description = "指定のバージョンを実行 migrate_force {version}"
args = [
  "-database",
  "${POSTGRES_URL}",
  "-path",
  "db/migrations",
  "force",
  "${@}"
]

[tasks.tbls]
command = "tbls"
description = "データベースドキュメントを生成する"
args = ["doc", "-f"]

[tasks.run]
command = "cargo"
description = "Graphqlサーバーの起動"
args = [
  "watch",
  "-x",
  "fmt",
  "-s",
  "mold -run cargo run --bin connefut_api", 
]

[tasks.schema]
command = "cargo"
description = "graphql.schemaに書き出す"
args = ["run", "--bin", "write_schema"]

[tasks.create_initial_data]
command = "cargo"
description = "初期データの生成"
args = ["run", "--bin", "initial_data"]
