[config]
skip_core_tasks = true

[tasks.migrate]
command = "psqldef"
description = "schema.sqlを参照してmigrateを実行する"
args = [
  "-U",
  "${POSTGRES_USER}",
  "-W",
  "${POSTGRES_PASSWORD}", 
  "-h",
  "${POSTGRES_HOST}",
  "-f",
  "./db/migration/schema.sql",
  "${POSTGRES_DB}"
]

[tasks.migrate_dry]
command = "psqldef"
description = "schema.sqlを参照してmigrateを実行する"
args = [
  "-U",
  "${POSTGRES_USER}",
  "-W",
  "${POSTGRES_PASSWORD}", 
  "-h",
  "${POSTGRES_HOST}",
  "-f",
  "./db/migration/schema.sql",
  "${POSTGRES_DB}",
  "--dry-run"
]

[tasks.tbls]
command = "tbls"
description = "データベースドキュメントを生成する"
args = ["doc", "-f"]

[tasks.run]
command = "cargo"
description = "Graphqlサーバーの起動"
args = [
  "watch",
  "-x",
  "fmt",
  "-s",
  "mold -run cargo run --bin connefut_api", 
]

[tasks.schema]
command = "cargo"
description = "graphql.schemaに書き出す"
args = ["run", "--bin", "write_schema"]

[tasks.init_data]
command = "cargo"
description = "初期データの生成"
args = ["run", "--bin", "initial_data"]
